
server:
  port: 8000
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      shutdown-timeout: 0
    timeout: 2000ms
  cache:
    type: redis
#自定义属性
custom:
  jwt:
    tokenHeader: Authorization
    expire_time: 1800000