
server:
  port: ${service-impl-user.server.port}
spring:
  application:
    name: service-impl-user
    qos:
      enable: true
      port: ${service-impl-user.application.qos.port}
  cloud:
    nacos:
      discovery:
        server-addr: ${spring.cloud.nacos.server.addr}
    alibaba:
      seata:
        tx-service-group: localhost_tx_group
dubbo:
  application:
    name: service-impl-user
  protocol:
    port: ${service-impl-user.dubbo.protocol.port}
    name: dubbo
  registry:
    address: ${spring.dubbo.registry.address}
    file: logs/dubbo-registry/service-impl-user.properties
  scan:
    base-packages: os.api.v2.service.impl.user.service
  consumer:
    check: false
seata:
  enabled: true
  registry:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.server.addr}
      application: seata-server
      username: nacos
      password: nacos
      group: SEATA_GROUP
  config:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.server.addr}
      application: seata-server
      dataId: seata-server.properties
      username: nacos
      password: nacos
      group: SEATA_GROUP